import allActions from "../data/allActions";

export const mockData = [
  {
    0: {
      player: 0,
      turn_num: 0,
      action: "Move Player",
      action_details: "Position 2",
      current_score: 0,
    },
    1: {
      player: 0,
      turn_num: 0,
      action: "Action Turn",
      action_details: "Action Turn",
      current_score: -1,
    },
    2: {
      player: 0,
      turn_num: 0,
      action: "End Turn",
      action_details: "End Turn",
      current_score: -2,
    },
    3: {
      player: 1,
      turn_num: 1,
      action: "Move Player",
      action_details: "Position 7",
      current_score: 0,
    },
    4: {
      player: 1,
      turn_num: 1,
      action: "Action Turn",
      action_details: "Action Turn",
      current_score: -1,
    },
    5: {
      player: 1,
      turn_num: 1,
      action: "End Turn",
      action_details: "End Turn",
      current_score: -2,
    },
    6: {
      player: 2,
      turn_num: 2,
      action: "Action Turn",
      action_details: "Action Turn",
      current_score: 0,
    },
    7: {
      player: 2,
      turn_num: 0,
      action: "Move Player",
      action_details: "Position 29",
      current_score: -2,
    },
    8: {
      player: 1,
      turn_num: 0,
      action: "Convey 1",
      action_details: "Second Card",
      current_score: -3,
    },
    meta_data: {
      player_0: 184,
      player_1: -11,
      player_2: -10,
      player_3: 87,
      player_4: 83,
    },
  },
  {
    0: {
      player: 0,
      turn_num: 0,
      action: "Action Turn",
      action_details: "Action Turn",
      current_score: 0,
    },
    1: {
      player: 0,
      turn_num: 0,
      action: "Fill Monument",
      action_details: "Generative Energy",
      current_score: -1,
    },
    2: {
      player: 0,
      turn_num: 0,
      action: "Move Player",
      action_details: "Position 21",
      current_score: -2,
    },
    3: {
      player: 0,
      turn_num: 0,
      action: "End Turn",
      action_details: "End Turn",
      current_score: -3,
    },
    4: {
      player: 1,
      turn_num: 1,
      action: "Action Turn",
      action_details: "Action Turn",
      current_score: 0,
    },
    5: {
      player: 1,
      turn_num: 1,
      action: "End Turn",
      action_details: "End Turn",
      current_score: -1,
    },
    6: {
      player: 2,
      turn_num: 2,
      action: "Action Turn",
      action_details: "Action Turn",
      current_score: 0,
    },
    7: {
      player: 2,
      turn_num: 2,
      action: "End Turn",
      action_details: "End Turn",
      current_score: -1,
    },
    8: {
      player: 3,
      turn_num: 3,
      action: "Action Turn",
      action_details: "Action Turn",
      current_score: 0,
    },
    9: {
      player: 0,
      turn_num: 3,
      action: "Move Player",
      action_details: "Position 14",
      current_score: -1,
    },
    10: {
      player: 3,
      turn_num: 3,
      action: "End Turn",
      action_details: "End Turn",
      current_score: -2,
    },
    11: {
      player: 4,
      turn_num: 4,
      action: "Convey Turn",
      action_details: "Convey Turn",
      current_score: 0,
    },
    12: {
      player: 4,
      turn_num: 4,
      action: "Convey 1",
      action_details: "Second Card",
      current_score: -1,
    },
    13: {
      player: 4,
      turn_num: 4,
      action: "End Turn",
      action_details: "End Turn",
      current_score: -2,
    },
    meta_data: {
      player_0: 184,
      player_1: -11,
      player_2: -10,
      player_3: 87,
      player_4: 83,
    },
  },
];

export const mockDataExEnd = [
  {
    0: {
      player: 0,
      turn_num: 0,
      action: "Move Player",
      action_details: "Position 2",
      current_score: 0,
    },
    3: {
      player: 1,
      turn_num: 1,
      action: "Move Player",
      action_details: "Position 7",
      current_score: 0,
    },
    7: {
      player: 2,
      turn_num: 0,
      action: "Move Player",
      action_details: "Position 29",
      current_score: -2,
    },
    8: {
      player: 1,
      turn_num: 0,
      action: "Convey 1",
      action_details: "Second Card",
      current_score: -3,
    },
    meta_data: {
      player_0: 184,
      player_1: -11,
      player_2: -10,
      player_3: 87,
      player_4: 83,
    },
  },
  {
    1: {
      player: 0,
      turn_num: 0,
      action: "Fill Monument",
      action_details: "Generative Energy",
      current_score: -1,
    },
    2: {
      player: 0,
      turn_num: 0,
      action: "Move Player",
      action_details: "Position 21",
      current_score: -2,
    },
    9: {
      player: 0,
      turn_num: 3,
      action: "Move Player",
      action_details: "Position 14",
      current_score: -1,
    },
    12: {
      player: 4,
      turn_num: 4,
      action: "Convey 1",
      action_details: "Second Card",
      current_score: -1,
    },
    meta_data: {
      player_0: 184,
      player_1: -11,
      player_2: -10,
      player_3: 87,
      player_4: 83,
    },
  },
];

export const mockDataMerged = [
  {
    0: {
      player: 0,
      turn_num: 0,
      action: "Move Player",
      action_details: "Move Player Position 2",
      current_score: 0,
    },
    3: {
      player: 1,
      turn_num: 1,
      action: "Move Player",
      action_details: "Move Player Position 7",
      current_score: 0,
    },
    7: {
      player: 2,
      turn_num: 0,
      action: "Move Player",
      action_details: "Move Player Position 29",
      current_score: -2,
    },
    8: {
      player: 1,
      turn_num: 0,
      action: "Convey 1",
      action_details: "Convey 1 Second Card",
      current_score: -3,
    },
    meta_data: {
      player_0: 184,
      player_1: -11,
      player_2: -10,
      player_3: 87,
      player_4: 83,
    },
  },
  {
    1: {
      player: 0,
      turn_num: 0,
      action: "Fill Monument",
      action_details: "Fill Monument Generative Energy",
      current_score: -1,
    },
    2: {
      player: 0,
      turn_num: 0,
      action: "Move Player",
      action_details: "Move Player Position 21",
      current_score: -2,
    },
    9: {
      player: 0,
      turn_num: 3,
      action: "Move Player",
      action_details: "Move Player Position 14",
      current_score: -1,
    },
    12: {
      player: 4,
      turn_num: 4,
      action: "Convey 1",
      action_details: "Convey 1 Second Card",
      current_score: -1,
    },
    meta_data: {
      player_0: 184,
      player_1: -11,
      player_2: -10,
      player_3: 87,
      player_4: 83,
    },
  },
];

export const mockSimulationData = {
  0: {
    0: {
      player: 0,
      turn_num: 0,
      action: "Move Player",
      action_details: "Move Player Position 2",
      current_score: 0,
    },
    3: {
      player: 1,
      turn_num: 1,
      action: "Move Player",
      action_details: "Move Player Position 7",
      current_score: 0,
    },
    7: {
      player: 2,
      turn_num: 0,
      action: "Move Player",
      action_details: "Move Player Position 29",
      current_score: -2,
    },
    8: {
      player: 1,
      turn_num: 0,
      action: "Convey 1",
      action_details: "Convey 1 Second Card",
      current_score: -3,
    },
    meta_data: {
      player_0: 184,
      player_1: -11,
      player_2: -10,
      player_3: 87,
      player_4: 83,
    },
  },
  1: {
    1: {
      player: 0,
      turn_num: 0,
      action: "Fill Monument",
      action_details: "Fill Monument Generative Energy",
      current_score: -1,
    },
    2: {
      player: 0,
      turn_num: 0,
      action: "Move Player",
      action_details: "Move Player Position 21",
      current_score: -2,
    },
    9: {
      player: 0,
      turn_num: 3,
      action: "Move Player",
      action_details: "Move Player Position 14",
      current_score: -1,
    },
    12: {
      player: 4,
      turn_num: 4,
      action: "Convey 1",
      action_details: "Convey 1 Second Card",
      current_score: -1,
    },
    meta_data: {
      player_0: 184,
      player_1: -11,
      player_2: -10,
      player_3: 87,
      player_4: 83,
    },
  },
};

export const mockPlayer0Data = {
  0: {
    player: 0,
    turn_num: 0,
    action: "Move Player",
    action_details: "Move Player Position 2",
    current_score: 0,
  },
};

export const mockFrequencyMap = [
  { name: "Action Tokens First Transmuter's Action Token", frequency: 0 },
  { name: "Action Tokens Second Transmuter's Action Token", frequency: 0 },
  { name: "Action Tokens Third Transmuter's Action Token", frequency: 0 },
  { name: "Action Tokens Forth Transmuter's Action Token", frequency: 0 },
  { name: "Action Tokens Fifth Transmuter's Action Token", frequency: 0 },
  { name: "Convey 1 First Card", frequency: 0 },
  { name: "Convey 1 Second Card", frequency: 0 },
  { name: "Convey 2 First Order", frequency: 0 },
  { name: "Convey 2 Second Order", frequency: 0 },
  { name: "Fill Monument Constructive Energy", frequency: 0 },
  { name: "Fill Monument Invertible Energy", frequency: 0 },
  { name: "Fill Monument Generative Energy", frequency: 0 },
  { name: "Fill Monument Primal Energy", frequency: 0 },

  { name: "Move Player Position 1", frequency: 0 },
  { name: "Move Player Position 2", frequency: 0 },
  { name: "Move Player Position 3", frequency: 0 },
  { name: "Move Player Position 4", frequency: 0 },
  { name: "Move Player Position 5", frequency: 0 },
  { name: "Move Player Position 6", frequency: 0 },
  { name: "Move Player Position 7", frequency: 0 },
  { name: "Move Player Position 8", frequency: 0 },
  { name: "Move Player Position 9", frequency: 0 },
  { name: "Move Player Position 10", frequency: 0 },
  { name: "Move Player Position 11", frequency: 0 },
  { name: "Move Player Position 12", frequency: 0 },
  { name: "Move Player Position 13", frequency: 0 },
  { name: "Move Player Position 14", frequency: 0 },
  { name: "Move Player Position 15", frequency: 0 },
  { name: "Move Player Position 16", frequency: 0 },
  { name: "Move Player Position 17", frequency: 0 },
  { name: "Move Player Position 18", frequency: 0 },
  { name: "Move Player Position 19", frequency: 0 },
  { name: "Move Player Position 20", frequency: 0 },
  { name: "Move Player Position 21", frequency: 0 },
  { name: "Move Player Position 22", frequency: 0 },
  { name: "Move Player Position 23", frequency: 0 },
  { name: "Move Player Position 24", frequency: 0 },
  { name: "Move Player Position 25", frequency: 0 },
  { name: "Move Player Position 26", frequency: 0 },
  { name: "Move Player Position 27", frequency: 0 },
  { name: "Move Player Position 28", frequency: 0 },
  { name: "Move Player Position 29", frequency: 0 },
  { name: "Move Player Position 30", frequency: 0 },
  { name: "Move Player Position 31", frequency: 0 },
  { name: "Move Player Position 32", frequency: 0 },
  { name: "Move Player Position 33", frequency: 0 },
  { name: "Move Player Position 34", frequency: 0 },
  { name: "Move Player Position 35", frequency: 0 },
  { name: "Move Player Position 36", frequency: 0 },
  { name: "Move Player Position 37", frequency: 0 },
  { name: "Move Player Position 38", frequency: 0 },
  { name: "Move Player Position 39", frequency: 0 },
  { name: "Move Player Position 40", frequency: 0 },
  { name: "Action Turn Action Turn", frequency: 0 },
  { name: "Convey Turn Convey Turn", frequency: 0 },
  { name: "End Turn End Turn", frequency: 0 },
];

export const mockCountMap = [
  { name: "Action Tokens First Transmuter's Action Token", count: 0 },
  { name: "Action Tokens Second Transmuter's Action Token", count: 0 },
  { name: "Action Tokens Third Transmuter's Action Token", count: 0 },
  { name: "Action Tokens Forth Transmuter's Action Token", count: 0 },
  { name: "Action Tokens Fifth Transmuter's Action Token", count: 0 },
  { name: "Convey 1 First Card", count: 0 },
  { name: "Convey 1 Second Card", count: 0 },
  { name: "Convey 2 First Order", count: 0 },
  { name: "Convey 2 Second Order", count: 0 },
  { name: "Fill Monument Constructive Energy", count: 0 },
  { name: "Fill Monument Invertible Energy", count: 0 },
  { name: "Fill Monument Generative Energy", count: 0 },
  { name: "Fill Monument Primal Energy", count: 0 },

  { name: "Move Player Position 1", count: 0 },
  { name: "Move Player Position 2", count: 0 },
  { name: "Move Player Position 3", count: 0 },
  { name: "Move Player Position 4", count: 0 },
  { name: "Move Player Position 5", count: 0 },
  { name: "Move Player Position 6", count: 0 },
  { name: "Move Player Position 7", count: 0 },
  { name: "Move Player Position 8", count: 0 },
  { name: "Move Player Position 9", count: 0 },
  { name: "Move Player Position 10", count: 0 },
  { name: "Move Player Position 11", count: 0 },
  { name: "Move Player Position 12", count: 0 },
  { name: "Move Player Position 13", count: 0 },
  { name: "Move Player Position 14", count: 0 },
  { name: "Move Player Position 15", count: 0 },
  { name: "Move Player Position 16", count: 0 },
  { name: "Move Player Position 17", count: 0 },
  { name: "Move Player Position 18", count: 0 },
  { name: "Move Player Position 19", count: 0 },
  { name: "Move Player Position 20", count: 0 },
  { name: "Move Player Position 21", count: 0 },
  { name: "Move Player Position 22", count: 0 },
  { name: "Move Player Position 23", count: 0 },
  { name: "Move Player Position 24", count: 0 },
  { name: "Move Player Position 25", count: 0 },
  { name: "Move Player Position 26", count: 0 },
  { name: "Move Player Position 27", count: 0 },
  { name: "Move Player Position 28", count: 0 },
  { name: "Move Player Position 29", count: 0 },
  { name: "Move Player Position 30", count: 0 },
  { name: "Move Player Position 31", count: 0 },
  { name: "Move Player Position 32", count: 0 },
  { name: "Move Player Position 33", count: 0 },
  { name: "Move Player Position 34", count: 0 },
  { name: "Move Player Position 35", count: 0 },
  { name: "Move Player Position 36", count: 0 },
  { name: "Move Player Position 37", count: 0 },
  { name: "Move Player Position 38", count: 0 },
  { name: "Move Player Position 39", count: 0 },
  { name: "Move Player Position 40", count: 0 },
  { name: "Action Turn Action Turn", count: 0 },
  { name: "Convey Turn Convey Turn", count: 0 },
  { name: "End Turn End Turn", count: 0 },
];

export const mockFrequencyMapForPlayer0 = [
  { name: "Action Tokens First Transmuter's Action Token", frequency: 0 },
  { name: "Action Tokens Second Transmuter's Action Token", frequency: 0 },
  { name: "Action Tokens Third Transmuter's Action Token", frequency: 0 },
  { name: "Action Tokens Forth Transmuter's Action Token", frequency: 0 },
  { name: "Action Tokens Fifth Transmuter's Action Token", frequency: 0 },
  { name: "Convey 1 First Card", frequency: 0 },
  { name: "Convey 1 Second Card", frequency: 0 },
  { name: "Convey 2 First Order", frequency: 0 },
  { name: "Convey 2 Second Order", frequency: 0 },
  { name: "Fill Monument Constructive Energy", frequency: 0 },
  { name: "Fill Monument Invertible Energy", frequency: 0 },
  { name: "Fill Monument Generative Energy", frequency: 1 },
  { name: "Fill Monument Primal Energy", frequency: 0 },

  { name: "Move Player Position 1", frequency: 0 },
  { name: "Move Player Position 2", frequency: 1 },
  { name: "Move Player Position 3", frequency: 0 },
  { name: "Move Player Position 4", frequency: 0 },
  { name: "Move Player Position 5", frequency: 0 },
  { name: "Move Player Position 6", frequency: 0 },
  { name: "Move Player Position 7", frequency: 0 },
  { name: "Move Player Position 8", frequency: 0 },
  { name: "Move Player Position 9", frequency: 0 },
  { name: "Move Player Position 10", frequency: 0 },
  { name: "Move Player Position 11", frequency: 0 },
  { name: "Move Player Position 12", frequency: 0 },
  { name: "Move Player Position 13", frequency: 0 },
  { name: "Move Player Position 14", frequency: 1 },
  { name: "Move Player Position 15", frequency: 0 },
  { name: "Move Player Position 16", frequency: 0 },
  { name: "Move Player Position 17", frequency: 0 },
  { name: "Move Player Position 18", frequency: 0 },
  { name: "Move Player Position 19", frequency: 0 },
  { name: "Move Player Position 20", frequency: 0 },
  { name: "Move Player Position 21", frequency: 1 },
  { name: "Move Player Position 22", frequency: 0 },
  { name: "Move Player Position 23", frequency: 0 },
  { name: "Move Player Position 24", frequency: 0 },
  { name: "Move Player Position 25", frequency: 0 },
  { name: "Move Player Position 26", frequency: 0 },
  { name: "Move Player Position 27", frequency: 0 },
  { name: "Move Player Position 28", frequency: 0 },
  { name: "Move Player Position 29", frequency: 0 },
  { name: "Move Player Position 30", frequency: 0 },
  { name: "Move Player Position 31", frequency: 0 },
  { name: "Move Player Position 32", frequency: 0 },
  { name: "Move Player Position 33", frequency: 0 },
  { name: "Move Player Position 34", frequency: 0 },
  { name: "Move Player Position 35", frequency: 0 },
  { name: "Move Player Position 36", frequency: 0 },
  { name: "Move Player Position 37", frequency: 0 },
  { name: "Move Player Position 38", frequency: 0 },
  { name: "Move Player Position 39", frequency: 0 },
  { name: "Move Player Position 40", frequency: 0 },
  { name: "Action Turn Action Turn", frequency: 0 },
  { name: "Convey Turn Convey Turn", frequency: 0 },
  { name: "End Turn End Turn", frequency: 0 },
];

export const mockCountMapForPlayer0 = [
  { name: "Action Tokens First Transmuter's Action Token", count: 0 },
  { name: "Action Tokens Second Transmuter's Action Token", count: 0 },
  { name: "Action Tokens Third Transmuter's Action Token", count: 0 },
  { name: "Action Tokens Forth Transmuter's Action Token", count: 0 },
  { name: "Action Tokens Fifth Transmuter's Action Token", count: 0 },
  { name: "Convey 1 First Card", count: 0 },
  { name: "Convey 1 Second Card", count: 0 },
  { name: "Convey 2 First Order", count: 0 },
  { name: "Convey 2 Second Order", count: 0 },
  { name: "Fill Monument Constructive Energy", count: 0 },
  { name: "Fill Monument Invertible Energy", count: 0 },
  { name: "Fill Monument Generative Energy", count: 1 },
  { name: "Fill Monument Primal Energy", count: 0 },

  { name: "Move Player Position 1", count: 0 },
  { name: "Move Player Position 2", count: 1 },
  { name: "Move Player Position 3", count: 0 },
  { name: "Move Player Position 4", count: 0 },
  { name: "Move Player Position 5", count: 0 },
  { name: "Move Player Position 6", count: 0 },
  { name: "Move Player Position 7", count: 0 },
  { name: "Move Player Position 8", count: 0 },
  { name: "Move Player Position 9", count: 0 },
  { name: "Move Player Position 10", count: 0 },
  { name: "Move Player Position 11", count: 0 },
  { name: "Move Player Position 12", count: 0 },
  { name: "Move Player Position 13", count: 0 },
  { name: "Move Player Position 14", count: 1 },
  { name: "Move Player Position 15", count: 0 },
  { name: "Move Player Position 16", count: 0 },
  { name: "Move Player Position 17", count: 0 },
  { name: "Move Player Position 18", count: 0 },
  { name: "Move Player Position 19", count: 0 },
  { name: "Move Player Position 20", count: 0 },
  { name: "Move Player Position 21", count: 1 },
  { name: "Move Player Position 22", count: 0 },
  { name: "Move Player Position 23", count: 0 },
  { name: "Move Player Position 24", count: 0 },
  { name: "Move Player Position 25", count: 0 },
  { name: "Move Player Position 26", count: 0 },
  { name: "Move Player Position 27", count: 0 },
  { name: "Move Player Position 28", count: 0 },
  { name: "Move Player Position 29", count: 0 },
  { name: "Move Player Position 30", count: 0 },
  { name: "Move Player Position 31", count: 0 },
  { name: "Move Player Position 32", count: 0 },
  { name: "Move Player Position 33", count: 0 },
  { name: "Move Player Position 34", count: 0 },
  { name: "Move Player Position 35", count: 0 },
  { name: "Move Player Position 36", count: 0 },
  { name: "Move Player Position 37", count: 0 },
  { name: "Move Player Position 38", count: 0 },
  { name: "Move Player Position 39", count: 0 },
  { name: "Move Player Position 40", count: 0 },
  { name: "Action Turn Action Turn", count: 0 },
  { name: "Convey Turn Convey Turn", count: 0 },
  { name: "End Turn End Turn", count: 0 },
];

export const mockNonZeroFreqMapPlayer0 = [
  { name: "Fill Monument Generative Energy", frequency: 1 },
  { name: "Move Player Position 2", frequency: 1 },
  { name: "Move Player Position 14", frequency: 1 },
  { name: "Move Player Position 21", frequency: 1 },
];

export const mockScoresData = [
  {
    "Sim 0": {
      player_0: 184,
      player_1: -11,
      player_2: -10,
      player_3: 87,
      player_4: 83,
    },
  },
  {
    "Sim 1": {
      player_0: 184,
      player_1: -11,
      player_2: -10,
      player_3: 87,
      player_4: 83,
    },
  },
];

export const mockMapData = {
  "Turn 1, Move Player Position 2": 1,
  "End Game": 2,
  "Turn 1, Fill Monument Generative Energy": 1,
  "Turn 2, Move Player Position 21": 2,
  "Turn 3, Move Player Position 14": 3,
};

export const mockResultsData = [
  ["Turn 1, Move Player Position 2", "Turn 1, Fill Monument Generative Energy"],
  ["End Game", "Turn 2, Move Player Position 21"],
  ["Turn 3, Move Player Position 14"],
  ["End Game"],
  [],
];
